### ISSUE TITLE
Item is not returned to the option index after being removed from selection.

### ISSUE THREAD

**Issue by lorrenbiffin** [miguelcobain/ember-selectize#1]
When working with a multiple-select, removing an item from the current selection does not return that item to the option index. This can be resolved by changing line `137` from `[..] selectize.removeOption [..]` to `[..] selectize.addOption [..]`

**Comment by lorrenbiffin** [comment]
I would normally submit a pull-request, but I'm a bit short on time today. Thanks again for the great work here! :)

**Comment by miguelcobain** [comment]
Sorry, could you explain this in another way? I'm not getting there. :)

**Comment by lorrenbiffin** [comment]
Hey, no problem. :)

If I have a Selectize instance allowing multiple selections (for a hasMany relationship, for instance), and I delete one of the selected items from the selectize input, the item I removed from the selection is not returned to the available options (in the selectize drop-down). Changing removeOption to addOption fixes the issue for me.

**Comment by miguelcobain** [comment]
Of course this was a bug! I can't explain how I didn't notice this until now.

Acording to the docs, the correct method to use would be `removeItem`.
Please confirm if this works for you.

Thanks!

**Comment by miguelcobain** [comment]
Actually, I'm having some inconsistencies with `removeItem` as well. 
The problem is that `removeItem` triggers selectize's `onItemRemove` which triggers ember-selectize's `_onItemRemove`.

This indeed does not happen with `addOption`, probably because it doesn't trigger `_onItemRemove`. I've also noticed that ember-selectize is triggering unnecessary observers. This definitely needs some work. Stick with addOption for now.

**Comment by miguelcobain** [comment]
@lorrenbiffin, please use the latest commit.

I fixed a lot of bugs, and I believe this is working properly now.
Things are much more stable now.

**Comment by lorrenbiffin** [comment]
Hey, sorry I dropped off so long and couldn't help test. I'll use the most recent and submit any issues I find. :)
