### ISSUE TITLE
associating selectize with Ember object

### ISSUE THREAD

**Issue by artburkart** [miguelcobain/ember-selectize#31]
@miguelcobain
I was wondering if you think it would be worth it to add a parameter to `createAction`. 
I want to be able to have one selectize per item rendered on a page, but the solution I've found is a bit hacky.

In this example `newItem1` is a hash I use for the creation of a new item1 . In order to edit a specific item1, I have to iterate through all my item1s to find the one that is currently in `editMode`, so I can change its color.

``` js
        actions: {
            createItem1Type: function (val) {
                var edited = false;
                var item1s = this.model.get('item1s').toArray();
                this.get('item1TypesList').pushObject(val);
                item1s.forEach(function (item) {
                    if (item.get('editMode')) {
                        item.set('color', val);
                        edited = true;
                    }
                });
                if (edited) { return; }
                this.set('newItem1.color', val);
            }   
        }    
```

With the extra parameter, the code becomes

``` js
    actions: {
        createItem: function (val, obj) {
            this.get('item1TypesList').pushObject(val);
            if (obj) {
                 obj.set('color', val);
            } else {
                this.set('newItem1.color', val);
            }
        }
    }
```

which is a lot simpler and allows me to have more than one item in `editMode`. More importantly, I can accommodate more than one item type (ie. item1, item2, item2, etc) with just one `createAction`.

Cheers

**Comment by miguelcobain** [comment]
I'm sorry, but I'm not understanding which object you want to get passed to the create action.
Also, I'm not understanding the need of your `newItem1` hash.

Ideally, a simple jsfiddle would be great. If not possible, please try to better illustrate your code.
Sorry, but I think that there are more idiomatic ways to do this, and I need to understand the problem.

**Comment by artburkart** [comment]
I shouldn't try to explain things late at night after long days of coding. :stuck_out_tongue_closed_eyes:  Sorry to confuse.
It could very well be that my code is not idiomatic and I am simply creating problems for myself that shouldn't exist. If that's the case, I apologize for being off-topic.

Here's a [jsbin](http://emberjs.jsbin.com/fasem/1/edit?html,js,output) that might help clarify what I'm trying to accomplish. I'd like for the object I'm editing to get passed to the create action, so I can set its property without searching for it in my route model. Hopefully it makes more sense now.

Cheers

**Comment by miguelcobain** [comment]
I understand the fundamental problem.
Basically we have only one create action for all the loop-generated Ember.Selectize views. We need a way to distinguish them.

Right now, your code has a problem. Try to edit two Items simultaneously and create an item. Both items will get that property. This is because in your loop you're setting **all** the items with `editMode` = true.

Why don't we use all the Ember goodness? :smile: 
We need to encapsulate all this logic. Right now all the Item1 are backed by a single controller.

Ember is awesome. Here is your example, done with "the Ember way". Also added some "sugar" like `toggleProperty`; and when you set `createAction` you don't need `create=true`.

Also, using `{{render}}` helps to modularize your templates, making them more maintainable.

http://emberjs.jsbin.com/gicuyaleheto/1/edit?html,js,output

I :heart: Ember.

Tell me if you have any problems.

EDIT:
This gave me a cool idea. We could add a `target` in which ember selectize should call the action. Much like the normal actions have. In some situations we may want to trigger the action in a view, for example. But I'm pretty sure that triggering in the controller should be the way and the should be the default.

**Comment by artburkart** [comment]
I was literally reading about `{{render}}` as you were writing your response. I haven't used it yet. Once I realized it existed, I knew I was doing everything wrong, and then you come along and give me this beautiful example. 

Do you have a donate coffee button anywhere? I'd like to thank you! Your assistance goes well beyond your selectize plugin.

PS: I was aware that more than one item would get the property if `editMode` was true. In my code I was making sure that only one could be set to true at any one time, which is where I started to hate my solution and think that either I was doing something wrong or something was missing from the plugin.

**Comment by artburkart** [comment]
I did exactly what you suggested and it solved my problem. Thanks. :+1:

**Comment by miguelcobain** [comment]
Glad it helped. :)
