### ISSUE TITLE
Uncaught TypeError: Cannot read property 'proto' of undefined

### ISSUE THREAD

**Issue by imtapps** [miguelcobain/ember-selectize#7]
Thanks for the awesome project! I just dropped this in like so

``` js
{{view Ember.Selectize
contentBinding="controller.customers"
valueBinding="controller.selectedCustomer"
optionValuePath="content.id"
optionLabelPath="content.name"
placeholder="Select a customer"}}
```

On my controller side, I'm giving this drop down a list of ember-data objects to look through

``` js
customers: function() {
  return this.store.all('customer');
}.property()
```

I'm using ember.js 1.3.1 and when I boot into my view I get the following error

``` js
Uncaught TypeError: Cannot read property 'proto' of undefined
```

**Comment by miguelcobain** [comment]
Many thanks!

First of all, you should avoid to fetch models in controllers.
If you need additional auxiliary models besides your main route model, use the `setupController` hook to put models in your controllers.

Regarding your problem, I just updated to Ember 1.3.1 and the tests went fine. Are you sure this problem comes from Ember.Selectize? What if you use a regular array of objects with `id` and `name` properties instead of an "Ember Data" computed property?

**Comment by imtapps** [comment]
Wow -complete fail on my part. After looking at my Gruntfile again this morning, I typed the wrong js file to include completely (thanks for the help! and this awesome library!)

**Comment by miguelcobain** [comment]
Glad it worked for you.
